export const homeObjOne = {
id: 'about',
lightBg: false,
lightText: true,
lightTextDesc: true,
topLine: 'Premium Bank',
headline: 'Unlimited Transactions with zero fees',
description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis vero laboriosam eaque sapiente aspernatur voluptas accusantium dolores at id laborum, recusandae consequuntur sunt adipisci quam aliquam deserunt amet. Facilis, fugiat.',
buttonLabel: 'Get started',
imgStart: false,
img: require('../../images/svg-1.svg').default,
alt: 'Car',
dark: false,
primary: true,
darkText: false,
}

export const homeObjTwo = {
id: 'discover',
lightBg: true,
lightText: false,
lightTextDesc: false,
topLine: 'Premium Bank',
headline: 'Unlimited Transactions with zero fees',
description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis vero laboriosam eaque sapiente aspernatur voluptas accusantium dolores at id laborum, recusandae consequuntur sunt adipisci quam aliquam deserunt amet. Facilis, fugiat.',
buttonLabel: 'Get started',
imgStart: true,
img: require('../../images/svg-1.svg').default,
alt: 'Car',
dark: true,
primary: true,
darkText: true,
}

export const homeObjThree = {
id: 'services',
lightBg: false,
lightText: true,
lightTextDesc: true,
topLine: 'Premium Bank',
headline: 'Unlimited Transactions with zero fees',
description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis vero laboriosam eaque sapiente aspernatur voluptas accusantium dolores at id laborum, recusandae consequuntur sunt adipisci quam aliquam deserunt amet. Facilis, fugiat.',
buttonLabel: 'Get started',
imgStart: false,
img: require('../../images/svg-1.svg').default,
alt: 'Car',
dark: true,
primary: true,
darkText: false,
}